# Generated by Django 2.2.17 on 2021-02-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('picture', models.ImageField(default='languages/lan.jpg', upload_to='languages')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageRequest',
            fields=[
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('request_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=128, unique=True)),
                ('sessionID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('pageURL', models.CharField(max_length=128, unique=True)),
                ('language', models.CharField(max_length=128, unique=True)),
                ('location', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
