# Generated by Django 2.2.17 on 2021-02-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanex', '0002_auto_20210220_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagerequest',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lanex.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='languagerequest',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
