# Generated by Django 2.2.17 on 2021-02-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanex', '0003_auto_20210220_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagerequest',
            name='location',
        ),
        migrations.RemoveField(
            model_name='languagerequest',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='languagerequest',
            name='sessionID',
        ),
        migrations.RemoveField(
            model_name='languagerequest',
            name='time',
        ),
        migrations.AddField(
            model_name='languagerequest',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
