# Generated by Django 2.2.17 on 2021-02-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanex', '0004_auto_20210220_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images'),
        ),
    ]
